fn_args_layout="Tall"
format_code_in_doc_comments=true
indent_style="Block"
control_brace_style="AlwaysSameLine"
comment_width=80
max_width=100
error_on_line_overflow=true
newline_style="Unix"
normalize_comments=true
reorder_impl_items=true
reorder_imports=true
reorder_modules=true
spaces_around_ranges=false
hard_tabs=false
tab_spaces=4
trailing_comma="Never"
use_field_init_shorthand=true
use_small_heuristics="Default"
where_single_line=true
wrap_comments=true